<?php

namespace Proxies\__CG__\Blog\ModelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Img extends \Blog\ModelBundle\Entity\Img implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Blog\\ModelBundle\\Entity\\Img' . "\0" . 'id', '' . "\0" . 'Blog\\ModelBundle\\Entity\\Img' . "\0" . 'post', '' . "\0" . 'Blog\\ModelBundle\\Entity\\Img' . "\0" . 'imgPath', '' . "\0" . 'Blog\\ModelBundle\\Entity\\Img' . "\0" . 'dateAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Blog\\ModelBundle\\Entity\\Img' . "\0" . 'id', '' . "\0" . 'Blog\\ModelBundle\\Entity\\Img' . "\0" . 'post', '' . "\0" . 'Blog\\ModelBundle\\Entity\\Img' . "\0" . 'imgPath', '' . "\0" . 'Blog\\ModelBundle\\Entity\\Img' . "\0" . 'dateAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Img $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostId($postId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostId', [$postId]);

        return parent::setPostId($postId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostId', []);

        return parent::getPostId();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgPath($imgPath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgPath', [$imgPath]);

        return parent::setImgPath($imgPath);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgPath', []);

        return parent::getImgPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgs(\Blog\ModelBundle\Entity\Post $imgs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgs', [$imgs]);

        return parent::setImgs($imgs);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgs', []);

        return parent::getImgs();
    }

    /**
     * {@inheritDoc}
     */
    public function setPost(\Blog\ModelBundle\Entity\Post $post)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPost', [$post]);

        return parent::setPost($post);
    }

    /**
     * {@inheritDoc}
     */
    public function getPost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPost', []);

        return parent::getPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAt($dateAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAt', [$dateAt]);

        return parent::setDateAt($dateAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAt', []);

        return parent::getDateAt();
    }

}
